name: Docker Build And Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and Push Multi-Arch Docker Image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 \
          -t maneeshwije/personal-website:latest \
          --push .
